accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name='accounts'

urlpatterns=[
    path('student_signup',views.StudentSignupView.as_view(),name='student_signup'),
    path('student_signupdone',views.StudentSignupDoneView.as_view(),name='student_signupdone'),
    path('login',views.CustomLoginView.as_view(),name='login'),
    path('logout',auth_view.LogoutView.as_view(template_name='logout.html'),name='logout')
]

flatspotproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    #studentアプリのURLを登録する
    path('student/',include('studentapp.urls')),
    #freeschoolアプリのURLを登録する
    path('freeschool/',include('freeschoolapp.urls')),
    #accountsアプリのURLを登録する
    path('accounts/',include('accounts.urls')),
    
    #パスワードリセット関連の登録
    path('password_reset',auth_views.PasswordResetView.as_view(template_name='passwordreset.html'),name='password_reset'),
    path('password_reset/done',auth_views.PasswordResetDoneView.as_view(template_name='passwordresetsent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='passwordresetform.html'),name='password_reset_confirm'),
    path('reset/done',auth_views.PasswordResetCompleteView.as_view(template_name='passwordresetdone.html'),name='password_reset_complete'),
    
]
#mediaフォルダのURLを追加、開発環境では必要
urlpatterns+=static(
    #MEDIA_URLはmedia/
    settings.MEDIA_URL,
    #MEDIA_ROOTにはmediaフォルダのパスが入っている
    document_root=settings.MEDIA_ROOT)

studentapp/urls.py
from django.urls import path
from . import views

app_name='studentapp'

#URLパターンを登録するためのリスト
urlpatterns=[
    path('top',views.TopView.as_view(),name='top'),
    
    #サークル機能
    path('clublist',views.ClubListView.as_view(),name='clublist'),
    path('clubdetail/<int:pk>',views.ClubDetailView.as_view(),name='clubdetail'),
    path('clubrequest/<int:club_id>/',views.ClubRequestView.as_view(),name='clubrequest'),
    path('clubrequestdone',views.ClubRequestDoneView.as_view(),name='clubrequestdone'),
            #いいね機能
    path('clublike/<int:pk>',views.LikeForClubView.as_view(), name='clublike'),
    
    #イベント機能
    path('eventlist',views.EventListView.as_view(),name='eventlist'),
    path('eventdetail/<int:pk>',views.EventDetailView.as_view(),name='eventdetail'),
    path('eventrequest/<int:event_id>/',views.EventRequestView.as_view(),name='eventrequest'),
    path('eventrequestdone',views.EventRequestDoneView.as_view(),name='eventrequestdone'),
            #いいね機能
    path('eventlike/<int:pk>',views.LikeForEventView.as_view(), name='eventlike'),
    
    #ブログ機能
    path('bloglist',views.BlogListView.as_view(),name='bloglist'),
    path('blogdetail/<int:pk>',views.BlogDetailView.as_view(),name='blogdetail'),
        #いいね機能
    path('blogpostlike/<int:pk>',views.LikeForBlogView.as_view(), name='blogpostlike'),
    
    #お問い合わせ機能
    path('contact',views.ContactView.as_view(),name='contact'),
    path('contactdone',views.ContactDoneView.as_view(),name='contactdone'),
    
    #このサイトについて
    path('about',views.AboutView.as_view(),name='about'),
    
    #フリースクール情報を表示する画面
    path('freeschoolinfo/<int:pk>',views.FreeSchoolInfoView.as_view(),name='freeschoolinfo'),
    
    #マイページ機能
    path('mypage',views.MypageView.as_view(),name='mypage'),#アカウント情報表示
    path('mypageupdate',views.MypageUpdateView.as_view(),name='mypageupdate'),#アカウント情報変更
    path('mypagedeletecheck',views.MypageDeleteCheckView.as_view(),name='mypagedeletecheck'),#アカウント情報削除確認画面
    path('accountdelete',views.AccountDeleteView.as_view(),name='accountdelete'),#アカウントを削除する処理
    path('mypagedeletedone',views.MypageDeleteDoneView.as_view(),name='mypagedeletedone'),#アカウント削除完了画面
    #フリースクールアカウントかadminでアクセスしようとした時のエラーページ
    path('logouturge',views.LogoutUrgeView.as_view(),name='logouturge'),
]    

freeschoolapp/models.py
from django.db import models

#カスタムユーザーのサブクラスとして実装
from accounts.models import CustomUser
#電話番号のバリデーター
from django.core.validators import RegexValidator

class FreeSchool(models.Model):

    #CustomUserと1対多の関係にする、FreeSchoolが削除されたら親モデルも一緒に削除する
    user=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    
    #フリースクール名
    freeschool_name=models.CharField(max_length=50,null=False)
   
    #責任者の名前
    manager_name=models.CharField(max_length=40,null=False)
    
    #住所フィールド
    address=models.CharField(max_length=255,null=False)   
    
    def __str__(self):
        return self.freeschool_name  # 管理画面に表示する名前を freeschool_name に変更

class Club(models.Model):
    
    #CustomUserと1対多の関係にする、Clubが削除されたら親モデルも一緒に削除する
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    
    #サークル名
    club_name=models.CharField(max_length=50,null=False)
    
    #ジャンル
    category_choices=[
        ('culture','文化'),
        ('sports','運動'),
        ('study','勉強'),
        ('others','その他'),
    ]
    
    category=models.CharField(max_length=20,choices=category_choices)
    
    #代表者名
    REP=models.CharField(max_length=30,null=False)
    
    #メールアドレス
    email=models.EmailField(null=False)
    
    #電話番号
    phone_number = models.CharField(
        max_length=11,
        validators=[
            RegexValidator(regex=r"^\d+$", message="電話番号は半角数字11桁以内で入力してください。")
        ],
        unique=False,
        blank=False,
        null=False,
    )
    
    #日時
    date=models.CharField(max_length=30,null=False)
    
    #参加費
    fee=models.PositiveIntegerField(null=False)
    
    #場所
    place=models.CharField(max_length=50,null=False)
    
    #SNSリンク
    sns_link=models.URLField(null=False)
    
    #SNS名
    sns_name=models.CharField(max_length=30,null=False)
    
    #画像1~5
    image1=models.ImageField(blank=False,null=False,upload_to='photos')
    image2=models.ImageField(blank=True,null=True,upload_to='photos')
    image3=models.ImageField(blank=True,null=True,upload_to='photos')
    image4=models.ImageField(blank=True,null=True,upload_to='photos')
    image5=models.ImageField(blank=True,null=True,upload_to='photos')
    
    #公開状況
    public_flag=models.BooleanField(default=True)
    
    #サークルの紹介文
    detail_text=models.TextField(max_length=1000,blank=True,null=True)
    
    #作成日時
    created_at=models.DateTimeField(auto_now_add=True)
 
    #更新日時
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.club_name  # 管理画面に表示する名前をclub_nameに変更


class Event(models.Model):
    
    #CustomUserと1対多の関係にする、Eventが削除されたら親モデルも一緒に削除する
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    
    #イベント名
    event_name=models.CharField(max_length=50,null=False)
    
    #ジャンル
    category_choices=[
        ('culture','文化'),
        ('sports','運動'),
        ('study','勉強'),
        ('others','その他'),
    ]
    
    category=models.CharField(max_length=20,choices=category_choices)
    
    #代表者名
    REP=models.CharField(max_length=30,null=False)
    
    #メールアドレス
    email=models.EmailField(null=False)
    
    #電話番号
    phone_number = models.CharField(
        max_length=11,
        validators=[
            RegexValidator(regex=r"^\d+$", message="電話番号は半角数字11桁以内で入力してください。")
        ],
        unique=False,
        blank=False,
        null=False,
    )
    
    #日時
    date=models.CharField(max_length=30,null=False)
    
    #参加費
    fee=models.PositiveIntegerField(null=False)
    
    #場所
    place=models.CharField(max_length=50,null=False)
    
    #SNSリンク
    sns_link=models.URLField(null=False)
    
    #SNS名
    sns_name=models.CharField(max_length=30,null=False)
    
    #画像1~5
    image1=models.ImageField(blank=False,null=False,upload_to='photos')
    image2=models.ImageField(blank=True,null=True,upload_to='photos')
    image3=models.ImageField(blank=True,null=True,upload_to='photos')
    image4=models.ImageField(blank=True,null=True,upload_to='photos')
    image5=models.ImageField(blank=True,null=True,upload_to='photos')
    
    #公開状況
    public_flag=models.BooleanField(default=True)
    
    #イベントの紹介文
    detail_text=models.TextField(max_length=1000,blank=True,null=True)
    
    #作成日時
    created_at=models.DateTimeField(auto_now_add=True)
 
    #更新日時
    updated_at=models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.event_name  # 管理画面に表示する名前をevent_nameに変更

class BlogPost(models.Model):
   
    #投稿者を紐づける
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    
    #タイトル
    title=models.CharField(max_length=40,null=False)
    
    #ジャンル
    category_choices=[
        ('report','活動報告'),
        ('news','ニュース'),
    ]
    category=models.CharField(max_length=25,choices=category_choices)
    
    #画像1~5、1枚目は必須
    image1=models.ImageField(blank=False,null=False,upload_to='photos')
    image2=models.ImageField(blank=True,null=True,upload_to='photos')
    image3=models.ImageField(blank=True,null=True,upload_to='photos')
    image4=models.ImageField(blank=True,null=True,upload_to='photos')
    image5=models.ImageField(blank=True,null=True,upload_to='photos')
   
    #公開状況
    public_flag=models.BooleanField(default=True)
   
    #ブログ記事本文
    detail_text=models.TextField(max_length=1000,blank=True,null=True)
 
    #作成日時
    created_at=models.DateTimeField(auto_now_add=True)
 
    #更新日時
    updated_at=models.DateTimeField(auto_now=True)

    #管理画面に表示する名前をtitleに変更
    def __str__(self):
        return self.title 

studentapp/models.py
from django.db import models
#カスタムユーザーのサブクラスとして実装
from accounts.models import CustomUser
#サークル・イベント・ブログモデル
from freeschoolapp.models import Club,Event,BlogPost
#日付を取得する
from django.utils import timezone

class Student(models.Model):

    #CustomUserと1対1の関係にする、Studentが削除されたら親モデルも一緒に削除する
    user=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    
    #ニックネームを定義する
    nickname=models.CharField(unique=True,max_length=25)
    
    #保護者フラグ、デフォルトはFalse
    is_guardian=models.BooleanField(default=False)
   
    #閲覧権限フラグ、デフォルトはFalse
    is_view=models.BooleanField(default=False)
   
    # 性別フィールド（choicesを使用）
    GENDER_CHOICES=[
        ('male','男'),
        ('female','女'),
        ('unknown','不明'),
    ]

    gender=models.CharField(max_length=10,choices=GENDER_CHOICES,default='unknown')

    #入学年度
    ent_year=models.IntegerField()

    #生年月日フィールド
    date_of_birth=models.DateField()
   
    #配慮事項フィールド、テキスト形式で自由に入力できるようにする。
    consideration=models.TextField(max_length=1000,blank=True,null=True)
    
    #管理画面に表示する名前をnicknameに変更
    def __str__(self):
        return self.nickname
    
#ブログのいいね機能
class LikeForBlogPost(models.Model):
    #いいねの対象、元の投稿が削除されたらいいねも削除する
    target=models.ForeignKey(BlogPost,on_delete=models.CASCADE)
    #いいねしたユーザー
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    #いいねした日付
    timestamp=models.DateTimeField(default=timezone.now)
    #データベースの初期設定をするクラス
    class Meta:
        #同じユーザーが同じ記事に対していいねできないようにする
        constraints = [
            models.UniqueConstraint(fields=['target','user'], name='unique_like_for_blogpost')
        ]
    
    #管理画面に表示する名前をtargetに変更
    def __str__(self):
        return self.target.title
    
        
#サークルのいいね機能    
class LikeForClub(models.Model):
    #いいねの対象、元の投稿が削除されたらいいねも削除する
    target=models.ForeignKey(Club,on_delete=models.CASCADE)
    #いいねしたユーザー
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    #いいねした日付
    timestamp=models.DateTimeField(default=timezone.now)
    
    #データベースの初期設定をするクラス
    class Meta:
        #同じユーザーが同じ記事に対していいねできないようにする
        constraints = [
            models.UniqueConstraint(fields=['target','user'], name='unique_like_for_clubpost')
        ]
    #管理画面に表示する名前をtargetに変更
    def __str__(self):
        return self.target.club_name           

#イベントのイイネ機能
class LikeForEvent(models.Model):
    #いいねの対象、元の投稿が削除されたらいいねも削除する
    target=models.ForeignKey(Event,on_delete=models.CASCADE)
    #いいねしたユーザー
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    #いいねした日付
    timestamp=models.DateTimeField(default=timezone.now)
    
    #データベースの初期設定をするクラス
    class Meta:
        #同じユーザーが同じ記事に対していいねできないようにする
        constraints=[
            models.UniqueConstraint(fields=['target','user'], name='unique_like_for_eventpost')
        ]
    
    #管理画面に表示する名前をtargetに変更
    def __str__(self):
        return self.target.event_name

studentapp/forms.py
from django import forms
from django.core.mail.message import EmailMessage

from .models import Student,CustomUser

import datetime

#サークル主催者に体験申請のメールを送るフォーム
class ClubRequestForm(forms.Form):
    
    message=forms.CharField(
        label='メッセージ',
        #複数行にわたって入力できるように設定
        widget=forms.Textarea(attrs={'class':'form-control','rows': 5}),
        max_length=1000,
    )
    
    #不登校生徒とフリースクール関係者のメアドを引数で渡す
    def send_mail(self,sender_email,club_owner_email):
        
        subject="サークルに体験申請が来ました！"
        
        body="<h1><h1>"
        
        # メールの作成と送信
        email=EmailMessage(
            subject=subject,
            body=body,
            from_email=sender_email,
            to=[club_owner_email],
        )
        email.send()
        
#イベント主催者に参加申請のメールを送るフォーム
class EventRequestForm(forms.Form):
    
    message=forms.CharField(
        label='メッセージ',
        #複数行にわたって入力できるように設定
        widget=forms.Textarea(attrs={'class':'form-control','rows':5}),
        max_length=1000,
    )
    
    #不登校生徒とフリースクール関係者のメアドを引数で渡す
    def send_mail(self,sender_email,club_owner_email):
        
        subject="イベントに体験申請が来ました！"
        
        body="<h1><h1>"
        
        # メールの作成と送信
        email=EmailMessage(
            subject=subject,
            body=body,
            from_email=sender_email,
            to=[club_owner_email],
        )
        email.send()

#お問い合わせフォーム
class ContactForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス',max_length=255)
    title = forms.CharField(label='件名',max_length=100)
    message = forms.CharField(label='メッセージ',widget=forms.Textarea,max_length=1000)

    
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        
        self.fields['name'].widget.attrs['placeholder']='お名前を入力してください'
        self.fields['name'].widget.attrs['class']='form-control'
        
        self.fields['email'].widget.attrs['placeholder']='メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class']='form-control'
        
        self.fields['title'].widget.attrs['placeholder']='タイトルを入力してください'
        self.fields['title'].widget.attrs['class']='form-control'
        
        self.fields['message'].widget.attrs['placeholder']='メッセージを入力してください'
        self.fields['message'].widget.attrs['class']='form-control'

#CustomUserを変更するフォーム
class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        #表示するフィールド
        fields = ['login_id','phone_number']
        labels={
           'login_id':'ログインID',
           'phone_number':'電話番号',
        }
    

#Studentを変更するフォーム
class StudentForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        widget=forms.DateInput(
            attrs={'type': 'date'}  # HTML5のカレンダー入力を有効化
        ),
        label="誕生日"
    )
    class Meta:
        model=Student
        #表示するフィールド
        fields=['nickname','is_guardian','gender', 'ent_year', 'date_of_birth','consideration']
        labels={
           'nickname':'ニックネーム',
           'is_guardian':'保護者',
           'gender':'性別',
           'ent_year':'入学年度',
           'date_of_birth':'誕生日',
           'consideration':'配慮事項',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 現在の年月日を取得
        dt = datetime.datetime.now()
        now_month = dt.month
        now_year = dt.year if now_month >= 4 else dt.year - 1
        
        # 入学年度の選択肢生成（過去2年から今年まで）
        ent_year_choices = [(year, f"{year}年") for year in range(now_year - 2, now_year + 1)]
        self.fields['ent_year'].widget = forms.Select(choices=ent_year_choices)
        

studentapp/templates/student_base_anyone.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">

    <!--ブラウザの表示領域を設定-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}{% endblock %}</title>
    <!--bootstrap5.3のリンク-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
    <!--共通部分のcss-->
    <link href="{% static 'css/student.css' %}"  rel="stylesheet" />
    <!--継承先で追加でcssファイルを使用するときに使う-->
    {% block css %}{% endblock %}
</head>

<body>
    <!--タイトル-->
    <nav class="navbar navbar-expand-lg" style="background-color: #ffefd5;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'studentapp:top' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
              <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293z"/>
              <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293z"/>
            </svg>
            ふらっとすぽっと
          </a>
        </div>
    </nav>
      
    <!--ハンバーガーメニュー-->
    <div class="nav">
      <!-- ハンバーガーメニューの表示・非表示を切り替えるチェックボックス -->
      <input id="drawer_input" class="drawer_hidden" type="checkbox">
   
      <!-- ハンバーガーアイコン -->
      <label for="drawer_input" class="drawer_open"><span></span></label>
   
      <!-- メニュー -->
      <nav class="nav_content">
        <ul class="nav_list">
          <li class="nav_item"><a href="{% url 'studentapp:clublist' %}" style="text-decoration:none;">サークル</a></li>
          <li class="nav_item"><a href="{% url 'studentapp:eventlist' %}" style="text-decoration:none;">イベント</a></li>
          <li class="nav_item"><a href="{% url 'studentapp:bloglist' %}" style="text-decoration:none;">ブログ</a></li>
          <li class="nav_item"><a href="{% url 'studentapp:contact' %}" style="text-decoration:none;">お問い合わせ</a></li>
        </ul>
      </nav>
    </div>

    <!--アカウント-->
    <!--ログインされている場合-->
    {% if user.is_authenticated %}
        <!--利用者が不登校生徒の場合のみ表示-->
        {% if user.user_type == 'student' %}
        <div class="dropdown">
          <div class="account-button">
            <button class="login-signup-button dropdown-toggle" type="button" data-bs-toggle="dropdown">
                {{ user.student.nickname }}
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'studentapp:mypage' %}">アカウント情報</a></li>
              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">ログアウト</a></li>
            </ul>          
          </div>
        </div>
        {% endif %}
    {% else %}
      <div class="account-button">
        <a href="{% url 'accounts:login' %}?next={{ request.path }}">
            <button class="login-signup-button">
              ログイン/ユーザー登録
            </button>
        </a>
      </div>
    {% endif %}
    
    <!--各画面でデータベース更新があった場合、meesagesを表示する-->
    {% for message in messages %}
      <div class="messagetext">
          {{ message }}
      </div>
    {% endfor %}


    <!--各画面でヘッダーの設定をする-->
    {% block header %}{% endblock %}

    <!--各画面でコンテンツの設定をする-->
    {% block contents %}{% endblock %}
    
    <a href="#top" id="topbutton"><button>一番上に戻る</button></a>

    <!--フリースクール情報等-->
    <footer class="footer">
      <div class="footer-main">
          <h2 class="footer-logo">
              <a href="{% url 'studentapp:top' %}" style="text-decoration:none;">ふらっとすぽっと</a>
          </h2>
          <nav>
              <ul class="footer-menu">
                  <li><a href="{% url 'studentapp:clublist' %}">サークル</a></li>
                  <li><a href="{% url 'studentapp:eventlist' %}">イベント</a></li>
                  <li><a href="{% url 'studentapp:bloglist' %}">ブログ</a></li>
                  <li><a href="{% url 'studentapp:contact' %}">お問い合わせ</a></li>
              </ul>
          </nav>
      </div>
    </footer>
</body>
</html>

studentapp/templates/student_bloglist.html
{% extends 'student_base_anyone.html' %}
{% load static %}
{% block title %}ブログ記事一覧画面{% endblock %}
<!--リスト用のcssを割り当てる-->
{% block css %}<link href="{% static 'css/student_list.css' %}" rel="stylesheet"/>{% endblock %}
{% block contents %}
    <!--画面タイトル-->
    <div class="list-name">
        <h3>ブログ記事一覧</h3>
    </div>
    <form method="get" action="{% url 'studentapp:bloglist' %}" class="Genre-search">
        <label for="category">ジャンルの絞り込み:</label>
        <select name="category" id="category">
            <option value="">すべて</option>
            {% for value, label in category_choices %}
                <option value="{{ value }}" {% if selected_category == value %}selected{% endif %}>
                    {{ label }}
                </option>
            {% endfor %}
        </select>
        <button type="submit" class="genre-refine">絞り込み</button>
    </form>


    {% if object_list %}
        <!--object_listにデータがある場合-->

        <!--レコードを格納されたobject_listから
            レコードを1行ずつrecordに取り出す-->
        {% for record in object_list %}

            <!--ブログ一覧-->
            <div class="list-container">
                <img src="{{ record.image1.url }}"
                width="500" height="300">
                <div class="list-content">
                    <p class="list-genre">{{ record.get_category_display }}</p>
                    <a href="{% url 'studentapp:blogdetail' record.pk %}"
                        style="text-decoration:none;" class="list-title">
                        {{ record.title }}
                    </a>
                    <div class="list-infomation">
                        <p>掲載日: {{ record.created_at }}</p>
                    </div>
                </div>
            </div>

        {% endfor %}
    {% else %}
        <!--object_listが空だった場合-->
        <p class="ListNone">ブログ記事が掲載されていません</p>
    {% endif %}
    {% include "pagination.html" %}
{% endblock %}

studentapp/templates/student_clublist.html
{% extends 'student_base_anyone.html' %}
{% load static %}
{% block title %}サークル記事一覧画面{% endblock %}
{% block css %}<link href="{% static 'css/student_list.css' %}" rel="stylesheet"/>{% endblock %}
{% block contents %}

    <!--画面タイトル-->
    <div class="list-name">
        <h3>サークル一覧</h3>
    </div>

    <!--ジャンル選択・絞込みボタン-->
    <form method="get" action="{% url 'studentapp:clublist' %}" class="Genre-search">
        <label for="category">ジャンルの絞り込み</label>
        <select name="category" id="category">
            <option value="">すべて</option>
            {% for value, label in category_choices %}
                <option value="{{ value }}" {% if selected_category == value %}selected{% endif %}>
                    {{ label }}
                </option>
            {% endfor %}
        </select>
        <button type="submit" class="genre-refine">絞り込み</button>
    </form>
    
    {% if object_list %}
        <!--object_listにデータがある場合-->

        <!--レコードを格納されたobject_listから
            レコードを1行ずつrecordに取り出す-->
        {% for record in object_list %}

            <!--サークル一覧-->
            <div class="list-container">
                <img src="{{ record.image1.url }}"
                width="500" height="300">
                <div class="list-content">
                    <p class="list-genre">{{ record.get_category_display }}</p>
                    <a href="{% url 'studentapp:clubdetail' record.pk %}"
                        style="text-decoration:none;" class="list-title">
                        {{ record.club_name }}
                    </a>
                    <div class="list-infomation">
                        <p>掲載日: {{ record.created_at }}</p>
                        <p>団体名: {{ record.user.freeschool.freeschool_name }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <!--object_listが空だった場合-->
        <p class="ListNone">サークルが掲載されていません</p>
    {% endif %}
    {% include "pagination.html" %}

{% endblock %}

studentapp/templates/student_contactdone.html
{% extends 'student_base_anyone.html' %}
{% load static %}
{% block title %}お問い合わせ送信完了{% endblock %}
{% block contents %}


<a href="{% url 'studentapp:top' %}"><button>トップページへ戻る</button></a>
{% endblock %}

studentapp/templates/student_mypagedeletedone.html
{% extends 'student_base_anyone.html' %}
{% load static %}
{% block title %}アカウント削除完了画面{% endblock %}
{% block contents %}
<a href="{% url 'studentapp:top' %}" class="cssbutton">トップページへ戻る</a>
{% endblock %}