accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name='accounts'

urlpatterns=[
    path('student_signup',views.StudentSignupView.as_view(),name='student_signup'),
    path('student_signupdone',views.StudentSignupDoneView.as_view(),name='student_signupdone'),
    path('login',views.CustomLoginView.as_view(),name='login'),
    path('logout',auth_view.LogoutView.as_view(template_name='logout.html'),name='logout')
]

flatspotproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    #studentアプリのURLを登録する
    path('student/',include('studentapp.urls')),
    #freeschoolアプリのURLを登録する
    path('freeschool/',include('freeschoolapp.urls')),
    #accountsアプリのURLを登録する
    path('accounts/',include('accounts.urls')),
    
    #パスワードリセット関連の登録
    path('password_reset',auth_views.PasswordResetView.as_view(template_name='passwordreset.html'),name='password_reset'),
    path('password_reset/done',auth_views.PasswordResetDoneView.as_view(template_name='passwordresetsent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='passwordresetform.html'),name='password_reset_confirm'),
    path('reset/done',auth_views.PasswordResetCompleteView.as_view(template_name='passwordresetdone.html'),name='password_reset_complete'),
    
]
#mediaフォルダのURLを追加、開発環境では必要
urlpatterns+=static(
    #MEDIA_URLはmedia/
    settings.MEDIA_URL,
    #MEDIA_ROOTにはmediaフォルダのパスが入っている
    document_root=settings.MEDIA_ROOT)

studentapp/urls.py
from django.urls import path
from . import views

app_name='studentapp'

#URLパターンを登録するためのリスト
urlpatterns=[
    path('top',views.TopView.as_view(),name='top'),
    
    #サークル機能
    path('clublist',views.ClubListView.as_view(),name='clublist'),
    path('clubdetail/<int:pk>',views.ClubDetailView.as_view(),name='clubdetail'),
    path('clubrequest/<int:club_id>/',views.ClubRequestView.as_view(),name='clubrequest'),
    path('clubrequestdone',views.ClubRequestDoneView.as_view(),name='clubrequestdone'),
            #いいね機能
    path('clublike/<int:pk>',views.LikeForClubView.as_view(), name='clublike'),
    
    #イベント機能
    path('eventlist',views.EventListView.as_view(),name='eventlist'),
    path('eventdetail/<int:pk>',views.EventDetailView.as_view(),name='eventdetail'),
    path('eventrequest/<int:event_id>/',views.EventRequestView.as_view(),name='eventrequest'),
    path('eventrequestdone',views.EventRequestDoneView.as_view(),name='eventrequestdone'),
            #いいね機能
    path('eventlike/<int:pk>',views.LikeForEventView.as_view(), name='eventlike'),
    
    #ブログ機能
    path('bloglist',views.BlogListView.as_view(),name='bloglist'),
    path('blogdetail/<int:pk>',views.BlogDetailView.as_view(),name='blogdetail'),
        #いいね機能
    path('blogpostlike/<int:pk>',views.LikeForBlogView.as_view(), name='blogpostlike'),
    
    #お問い合わせ機能
    path('contact',views.ContactView.as_view(),name='contact'),
    path('contactdone',views.ContactDoneView.as_view(),name='contactdone'),
    
    #このサイトについて
    path('about',views.AboutView.as_view(),name='about'),
    
    #フリースクール情報を表示する画面
    path('freeschoolinfo/<int:pk>',views.FreeSchoolInfoView.as_view(),name='freeschoolinfo'),
    
    #マイページ機能
    path('mypage',views.MypageView.as_view(),name='mypage'),#アカウント情報表示
    path('mypageupdate',views.MypageUpdateView.as_view(),name='mypageupdate'),#アカウント情報変更
    path('mypagedeletecheck',views.MypageDeleteCheckView.as_view(),name='mypagedeletecheck'),#アカウント情報削除確認画面
    path('accountdelete',views.AccountDeleteView.as_view(),name='accountdelete'),#アカウントを削除する処理
    path('mypagedeletedone',views.MypageDeleteDoneView.as_view(),name='mypagedeletedone'),#アカウント削除完了画面
    #フリースクールアカウントかadminでアクセスしようとした時のエラーページ
    path('logouturge',views.LogoutUrgeView.as_view(),name='logouturge'),
]    

accounts/models.py
from django.db import models

#継承専用のユーザ作成用抽象クラス、マネージャーのベース
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,BaseUserManager
#UUIDフィールド
import uuid
#日付を取得する
from django.utils import timezone
#電話番号のバリデーター
from django.core.validators import RegexValidator

#カスタムユーザーのマネージャー
class CustomUserManager(BaseUserManager):

    #不登校生徒とフリースクール関係者のユーザーを作成するメソッド

    def create_user(self,login_id,password,**extra_fields):
        
        #ログインIDが設定されているか判別
        if not login_id:
            raise ValueError('ログインIDが設定されていません')
        
        #メールの正規化を行う
        extra_fields['email']=self.normalize_email(extra_fields.get('email'))
        
        #インスタンスを作成
        user=self.model(login_id=login_id,**extra_fields)
        #パスワードを設定する
        user.set_password(password)
        #データベースに格納する
        user.save(using=self._db)
        return user        
            
    #スーパーユーザーを作成する際のメソッド、設定時にlogin_idとpasswordを設定する
    def create_superuser(self,login_id,password,**extra_fields):
        
        #デフォルトでスタッフ権限と管理者権限をTrueとする
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        #スタッフ権限とスーパーユーザー権限がTrueかチェックする
        if extra_fields.get('is_staff') is not True:
            raise ValueError('is_staffはTrueにしてください')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('is_superuserはTrueにしてください')
        
        #メールの正規化を行う
        extra_fields['email']=self.normalize_email(extra_fields.get('email'))
        
        return self.create_user(login_id,password,**extra_fields)

#認証モデル、パスワードは暗黙的に定義されている
class CustomUser(AbstractBaseUser,PermissionsMixin):
    #UUIDを設定する
    uu_id=models.UUIDField(primary_key=True,default=uuid.uuid4)
    
    #ログインに使用するユーザーIDを設定する
    login_id=models.CharField(max_length=40,unique=True,null=False)
    
    #登録日
    date_joined=models.DateTimeField("登録日",default=timezone.now)
    
    #メールフィールド
    email=models.EmailField(unique=True)
    
    #電話番号フィールド
    phone_number=models.CharField(
        max_length=11,
        validators=[
            RegexValidator(regex=r"^\d+$", message="電話番号は半角数字11桁以内で入力してください。")
        ],
        unique=True,
        blank=True,
        null=True,
    )
    
    #利用者種別の選択肢
    user_type_choices=(
        ('student','不登校生徒'),
        ('freeschool','フリースクール関係者'),
    )
    
    #利用者種別
    user_type=models.CharField(max_length=20,choices=user_type_choices)
    
    #is_activeを追加
    is_active=models.BooleanField(default=True)
    
    #is_staffとis_superuserを追加
    is_staff=models.BooleanField(default=False)
    is_superuser=models.BooleanField(default=False)
    
    #ログインIDで認証
    USERNAME_FIELD='login_id'
    
    #ユーザー作成時に必須にする項目
    REQUIRED_FIELDS=['email'] 
    
    #データベースを操作するためのマネージャーを登録
    objects=CustomUserManager()

studentapp/models.py
from django.db import models
#カスタムユーザーのサブクラスとして実装
from accounts.models import CustomUser
#サークル・イベント・ブログモデル
from freeschoolapp.models import Club,Event,BlogPost
#日付を取得する
from django.utils import timezone

class Student(models.Model):

    #CustomUserと1対1の関係にする、Studentが削除されたら親モデルも一緒に削除する
    user=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    
    #ニックネームを定義する
    nickname=models.CharField(unique=True,max_length=25)
    
    #保護者フラグ、デフォルトはFalse
    is_guardian=models.BooleanField(default=False)
   
    #閲覧権限フラグ、デフォルトはFalse
    is_view=models.BooleanField(default=False)
   
    # 性別フィールド（choicesを使用）
    GENDER_CHOICES=[
        ('male','男'),
        ('female','女'),
        ('unknown','不明'),
    ]

    gender=models.CharField(max_length=10,choices=GENDER_CHOICES,default='unknown')

    #入学年度
    ent_year=models.IntegerField()

    #生年月日フィールド
    date_of_birth=models.DateField()
   
    #配慮事項フィールド、テキスト形式で自由に入力できるようにする。
    consideration=models.TextField(max_length=1000,blank=True,null=True)
    
    #管理画面に表示する名前をnicknameに変更
    def __str__(self):
        return self.nickname
    
#ブログのいいね機能
class LikeForBlogPost(models.Model):
    #いいねの対象、元の投稿が削除されたらいいねも削除する
    target=models.ForeignKey(BlogPost,on_delete=models.CASCADE)
    #いいねしたユーザー
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    #いいねした日付
    timestamp=models.DateTimeField(default=timezone.now)
    #データベースの初期設定をするクラス
    class Meta:
        #同じユーザーが同じ記事に対していいねできないようにする
        constraints = [
            models.UniqueConstraint(fields=['target','user'], name='unique_like_for_blogpost')
        ]
    
    #管理画面に表示する名前をtargetに変更
    def __str__(self):
        return self.target.title
    
        
#サークルのいいね機能    
class LikeForClub(models.Model):
    #いいねの対象、元の投稿が削除されたらいいねも削除する
    target=models.ForeignKey(Club,on_delete=models.CASCADE)
    #いいねしたユーザー
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    #いいねした日付
    timestamp=models.DateTimeField(default=timezone.now)
    
    #データベースの初期設定をするクラス
    class Meta:
        #同じユーザーが同じ記事に対していいねできないようにする
        constraints = [
            models.UniqueConstraint(fields=['target','user'], name='unique_like_for_clubpost')
        ]
    #管理画面に表示する名前をtargetに変更
    def __str__(self):
        return self.target.club_name           

#イベントのイイネ機能
class LikeForEvent(models.Model):
    #いいねの対象、元の投稿が削除されたらいいねも削除する
    target=models.ForeignKey(Event,on_delete=models.CASCADE)
    #いいねしたユーザー
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    #いいねした日付
    timestamp=models.DateTimeField(default=timezone.now)
    
    #データベースの初期設定をするクラス
    class Meta:
        #同じユーザーが同じ記事に対していいねできないようにする
        constraints=[
            models.UniqueConstraint(fields=['target','user'], name='unique_like_for_eventpost')
        ]
    
    #管理画面に表示する名前をtargetに変更
    def __str__(self):
        return self.target.event_name

accounts/forms.py
from django import forms
from accounts.models import CustomUser
from studentapp.models import Student
from freeschoolapp.models import FreeSchool
from phonenumber_field.formfields import PhoneNumberField

#時刻関連
import datetime

#共通のサインアップフォーム
class SignupForm(forms.ModelForm):

    # パスワードを再確認するフィールドを追加
    password=forms.CharField(widget=forms.PasswordInput,label='パスワード')
    confirm_password=forms.CharField(widget=forms.PasswordInput,label='パスワード(確認)')
    
    #メタクラス
    class Meta:
        model=CustomUser
        #フォームを表示する項目、利用者種別は表示しない
        fields=['login_id','email','phone_number','password']
        #画面に表示するラベルを設定する
        labels={
            'login_id':'ログインID',
            'email':'メールアドレス',
            'phone_number':'電話番号',
        }
    
    # パスワードのバリデーション
    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise forms.ValidationError("パスワードは8文字以上である必要があります。")
        return password

    #バリデーションを実行
    def clean(self):
        cleaned_data=super().clean()
        #パスワード(1回目)
        password=cleaned_data.get("password")
        #パスワード(再確認)
        confirm_password=cleaned_data.get("confirm_password")
        
        login_id = cleaned_data.get("login_id")
        email = cleaned_data.get("email")
        phone_number = cleaned_data.get("phone_number")

        if password!=confirm_password:
            self.add_error('confirm_password',"パスワードが一致しません。")
        
        if CustomUser.objects.filter(login_id=login_id).exists():
            self.add_error('login_id', "このIDは既に使用されています。")

        if CustomUser.objects.filter(email=email).exists():
            self.add_error('email', "このメールアドレスは既に登録されています。")

        if phone_number!=None:
            if CustomUser.objects.filter(phone_number=phone_number).exists():
                self.add_error('phone_number', "この電話番号は既に登録されています。")
        
        return cleaned_data
    

#不登校生徒用のサインアップフォーム
class StudentSignupForm(forms.ModelForm):
    class Meta:
        model=Student
        #表示するフィールド
        fields=['nickname','gender','ent_year','is_guardian','date_of_birth','consideration']
        #画面に表示するラベルを設定する
        labels={
            'nickname':'ニックネーム',
            'gender':'性別',
            'ent_year':'入学年度',
            'is_guardian':'保護者の方はチェックしてください',
            'date_of_birth':'誕生日',
            'consideration':'配慮事項'
        }
    # 日付を選択できるフォームフィールド
    date_of_birth=forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))    
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
   
        #現在の年月日を取得し、保存する
        dt=datetime.datetime.now()
        #現在の月を取得する
        now_month=dt.month
        #4月~12月と1月~3月で処理を分岐させる
        if now_month >= 4:
        #現在の年を取得する
            now_year=dt.year
        else:
        #現在の年－1を取得する
            now_year=dt.year-1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        #選択肢を生成
        ent_year_choices=[(year,f"{year}年") for year in range(now_year-2,now_year+1)]
        
        self.fields['ent_year'].widget=forms.Select(choices=ent_year_choices)
        
        #性別のラジオボタン、選択肢はStudenモデルから持ってきた
        self.fields['gender'].widget=forms.RadioSelect(choices=Student.GENDER_CHOICES)
    
    def clean(self):
        cleaned_data=super().clean()
        nickname = cleaned_data.get("nickname")
        
        if Student.objects.filter(nickname=nickname).exists():
            self.add_error('nickname', "このニックネームは既に使用されています。")
        return cleaned_data
        
            
#フリースクール関係者用のサインアップフォーム(現時点だと使う必要なし)
class FreeSchoolSignupForm(forms.ModelForm):
    class Meta:
        model=FreeSchool
        #表示するフィールド
        fields=['freeschool_name','manager_name','address']
    
    

accounts/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView,View
from django.urls import reverse_lazy
#リダイレクト
from django.shortcuts import redirect
#Django標準のログインビュー
from django.contrib.auth.views import LoginView
#forms.pyで定義したフォーム
from .forms import SignupForm,StudentSignupForm,FreeSchoolSignupForm


#LoginViewを利用者別で変えられるように判別、'login.html'を描画する
class CustomLoginView(LoginView):
    template_name='login.html'
    def get_redirect_url(self):
        user=self.request.user
        next_url = self.request.GET.get('next')  # nextパラメータを取得
        #ユーザー認証が成功されている場合
        if user.is_authenticated:
            #利用者種別によって遷移されるページを変える
            if user.user_type=='student':
                if next_url:
                    return next_url
                return '../student/top'
            if user.user_type=='freeschool':
                return '../freeschool/top'
        return super().get_redirect_url()

#student_signupdone.htmlを描画する
class StudentSignupDoneView(TemplateView):
    template_name='student_signupdone.html'

#不登校生徒用のサインアップビューを追加
class StudentSignupView(View):
    
    #サインアップフォームを表示する処理
    def get(self,request,*args,**kwargs):
        #CustomUserを作成するフォーム
        user_form=SignupForm()
        #Studentを作成するフォーム
        student_form=StudentSignupForm()

        #signup.htmlにフォームをレンダリングする
        return render(request,'student_signup.html',{
            'user_form':user_form,
            'student_form':student_form,
        })
        
    #サインアップする処理
    def post(self,request,*args,**kwargs):
        user_form= SignupForm(request.POST)
        student_form=StudentSignupForm(request.POST)
        
        # エラーが発生した場合のログ出力
        if not user_form.is_valid() or not student_form.is_valid():     
            print(user_form.errors)    
            print(student_form.errors)
        
        #バリデーションチェックを通った場合のみ処理する
        if user_form.is_valid() and student_form.is_valid():
            
            #CustomUserを作成する
            #コミットがTrueだと二重に保存されてしまうためFalseに設定する
            user=user_form.save(commit=False)
            #利用者種別を不登校生徒に固定
            user.user_type='student'
            #パスワードをハッシュ化
            user.set_password(user_form.cleaned_data['password'])
            user.save()
            
            #StudentUserを作成する
            #コミットがTrueだと二重に保存されてしまうためFalseに設定する
            student=student_form.save(commit=False)
            #CustomUserと関連付けする
            student.user=user
            student.save()
            
            #signupdoneにリダイレクトする
            return redirect('accounts:student_signupdone')            
        
        #フォームが無効の場合再描画する
        return render(request,'student_signup.html',{
            'user_form':user_form,
            'student_form':student_form,
        })

accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ログイン</title>
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
</head>
<body>
    <div class="login-form">
        <div class="form-group">
            <form method="post" id="requestForm">
                {% csrf_token %}
                {% if form.errors %}
                    正しいログインIDとパスワードを入力してください。大文字と小文字は区別されます。
                {% endif %}
                <label>ログインID:</label>
                {{ form.username }}
                <br>
                <label>パスワード:</label>
                {{ form.password }}
                <br><br>
                <!-- リダイレクト用の hidden フィールド -->
                <input type="hidden" name="next" id="next-url" value="">

                <button type="submit" class="login-button" id="submitButton">ログイン</button>
            </form>

            <script>
                // ページ読み込み時に hidden フィールドに現在のURLを設定
                window.onload=function() {
                    document.getElementById('next-url').value=window.location.href;
                };
            
                // フォーム送信前にURLを更新 (必要に応じて)
                document.getElementById('submitButton').addEventListener('click', function(event) {
                    document.getElementById('next-url').value=window.location.href; // 必要であれば更新
                });
            </script>
            

            <!--2重submitを防止する処理-->
            <script>
                const form = document.getElementById("requestForm");
                const submitButton = document.getElementById("submitButton");

                form.addEventListener("submit", function(event){
                    submitButton.disabled = true;//ボタンを無効化
                });
            </script>

            <br>
            <div class=""><a href="{% url 'accounts:student_signup' %}"><button class="signup-button">ユーザー登録</button></a></div>
            <br>
            <div class=""><a href="{% url 'password_reset' %}">パスワードをお忘れの方</a></div>
        </div>
    </div>
</body>
</html>

accounts/templates/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ログアウト</title>
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
</head>
<body>
    ログアウトしました
    <a href="{% url 'studentapp:top' %}">トップページへ戻る</a>
</body>
</html>
<!-- テストコメント -->

accounts/templates/passwordreset.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>パスワードをお忘れの方</title>
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
</head>
<body>
    <br><br>
    <form action="" method="POST" id="requestForm">
        {% csrf_token %}
        <!-- <div>
            {{form}}
            <br><br>
            <input type="submit" value="メールを受け取る"/>
        </div> -->
        <div>
            {{ form.email.label_tag }}
            {{form.email}}
            <br><br>
            <input type="submit" id="submitButton" value="メールを受け取る"/>
        </div>
    </form>

    <!--2重submitを防止する処理-->
    <script>
        const form = document.getElementById("requestForm");
        const submitButton = document.getElementById("submitButton");

        form.addEventListener("submit", function(event){
            submitButton.disabled = true;//ボタンを無効化
        });
    </script>

</body>
</html>

accounts/templates/passwordresetdone.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>パスワード再設定完了</title>
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
</head>
<body>
    <br><br>
    <div style="text-align: center;">
        パスワードリセット完了
        <br><br>
        <a href="{% url 'accounts:login' %}"><button class="button">ログイン画面へ</button></a>
        </div>
</body>
</html>

accounts/templates/passwordresetform.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>パスワード再設定</title>
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
</head>
<body>
    <br><br>
    <form action="" method="POST" id="requestForm">
        <div>
            {% csrf_token %}
            <!-- {{form}} -->
            {{form.new_password1.label_tag}}
            {{form.new_password1}}
            <br><br> 
            {{form.new_password2.label_tag}}
            {{form.new_password2}}
            {{form.errors.new_password2}}
            <br><br>
            <input type="submit" id="submitButton" value="再設定する"/>
        </div>
    </form>

    <!--2重submitを防止する処理-->
    <script>
        const form = document.getElementById("requestForm");
        const submitButton = document.getElementById("submitButton");

        form.addEventListener("submit", function(event){
            submitButton.disabled = true;//ボタンを無効化
        });
    </script>    

</body>
</html>

accounts/templates/passwordresetsent.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>メール送信完了</title>
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
</head>
<body>
    <br><br>
    <div style="text-align: center;">
    メール送信完了
    <br><br>
    <a href="{% url 'password_reset' %}"><button class="button">メールを再送信する</button></a>
    <br><br>
    <a href="{% url 'accounts:login' %}"><button class="button">ログイン画面へ戻る</button></a>
    </div>
</body>
</html>

accounts/templates/student_signup.html
{% load static %}
<!DOCTYPE html>
<link rel="stylesheet" href="{% static 'css/accounts.css'%}">
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>サインアップ</title>
</head>
<body class="signup_body">
    <form method="POST" class="student_signup" id="requestForm">
    <a href="{% url 'studentapp:top' %}" class="upperlefttopbutton2">トップページに戻る</a>
    <p>新規登録するアカウントの情報を入力してください</p>
    {% csrf_token %}
    <div class="labelandform">
        <div>
            <label for="id_login_id" class="required">ログインID</label>
            {{ user_form.login_id}} 
        </div>
        <div style="color:red;">{{ user_form.errors.login_id }}</div>
        <div>
            <label for="id_email" class="required">メールアドレス</label>
            {{ user_form.email }}
        </div>
        <div style="color:red;">{{ user_form.errors.email }}</div>
        <div>
            <label for="id_phone_number" class="optional">電話番号</label>
            {{ user_form.phone_number }}
        </div>
        <div style="color:red;">{{ user_form.errors.phone_number }}</div>
        <div>
            <label for="id_password" class="required">パスワード</label>
            {{ user_form.password }}
        </div>
        <div style="color:red;">{{ user_form.errors.password }}</div>
        <div>
            <label for="id_confirm_password" class="required">パスワード（確認）</label>
            {{ user_form.confirm_password }}
        </div>
        <div style="color:red;">{{ user_form.errors.confirm_password }}</div>
        <div>
            <label for="id_nickname" class="required">ニックネーム</label>
            {{ student_form.nickname }}
        </div>
        <div style="color:red;">{{ student_form.errors.nickname }}</div>
        <div class="gender_radio">
            <label for="id_gender_label">性別<span style="color:black;">（選択）</span></label> 
            <div id="id_gender"> </div>
            {{ student_form.gender }}  <!-- ラジオボタンを表示 -->
            {{ student_form.gender.errors }} <!-- バリデーションエラー表示 -->
        </div>
        <div>
            <label for="id_ent_year">入学年度<span style="color:black;">（選択）</span></label>
            {{ student_form.ent_year }}
        </div>
        <div>
            <label for="id_is_guardian">保護者の方はチェック<br>してください<span style="color:black;">（選択）</span></label>
            {{ student_form.is_guardian }}
        </div>
        <div>
            <label for="id_date_of_birth" class="required">生年月日</label>
            {{ student_form.date_of_birth }}
        </div>
        <div>
            <label for="id_consideration" class="optional">配慮事項</label>
            {{ student_form.consideration }}
        </div>
    </div>
    <button type="submit" id="submitButton" class="signup_button">★新規登録★</button>
    </form>

    <!--2重submitを防止する処理-->
    <script>
        const form = document.getElementById("requestForm");
        const submitButton = document.getElementById("submitButton");

        form.addEventListener("submit", function(event){
            submitButton.disabled = true;//ボタンを無効化
        });
    </script>

</body>
</html>

accounts/templates/student_signupdone.html
{% load static %}
<!DOCTYPE html>
<link rel="stylesheet" href="{% static "css/accounts.css" %}" >
<html>
    <head>
        <title>ユーザー登録完了画面</title>

    </head>

    <body>
        <div class="singupdone">
            <h1>ユーザー登録が完了しました</h1>
            <a href="{% url 'studentapp:top' %}"><button class="singupdonebutton">トップページに進む</button></a>
        </div>
    </body>

</html>