accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name='accounts'

urlpatterns=[
    path('student_signup',views.StudentSignupView.as_view(),name='student_signup'),
    path('student_signupdone',views.StudentSignupDoneView.as_view(),name='student_signupdone'),
    path('login',views.CustomLoginView.as_view(),name='login'),
    path('logout',auth_view.LogoutView.as_view(template_name='logout.html'),name='logout')
]

flatspotproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    #studentアプリのURLを登録する
    path('student/',include('studentapp.urls')),
    #freeschoolアプリのURLを登録する
    path('freeschool/',include('freeschoolapp.urls')),
    #accountsアプリのURLを登録する
    path('accounts/',include('accounts.urls')),
    
    #パスワードリセット関連の登録
    path('password_reset',auth_views.PasswordResetView.as_view(template_name='passwordreset.html'),name='password_reset'),
    path('password_reset/done',auth_views.PasswordResetDoneView.as_view(template_name='passwordresetsent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='passwordresetform.html'),name='password_reset_confirm'),
    path('reset/done',auth_views.PasswordResetCompleteView.as_view(template_name='passwordresetdone.html'),name='password_reset_complete'),
    
]
#mediaフォルダのURLを追加、開発環境では必要
urlpatterns+=static(
    #MEDIA_URLはmedia/
    settings.MEDIA_URL,
    #MEDIA_ROOTにはmediaフォルダのパスが入っている
    document_root=settings.MEDIA_ROOT)

freeschoolapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='freeschoolapp'

#URLパターンを登録するためのリスト
urlpatterns=[
    path('top',views.TopView.as_view(),name='top'),
    
    #マイページ機能
    path('mypage',views.MypageView.as_view(),name='mypage'),#アカウント情報表示
    path('mypageupdate',views.MypageUpdateView.as_view(),name='mypageupdate'),#アカウント情報変更
    #ユーザー検索画面(閲覧権限)
    path('usersearch',views.UserSearchView.as_view(),name='usersearch'),
    path('userdetail/<int:pk>/',views.UserDetailView.as_view(),name='userdetail'),
    #サークル機能
    path('clubpost',views.ClubPostView.as_view(),name='clubpost'),
    path('clubpostdone',views.ClubPostDoneView.as_view(),name='clubpostdone'),
    path('myclublist',views.MyClubListView.as_view(),name='myclublist'),
    path('myclubdetail/<int:pk>',views.MyClubDetailView.as_view(),name='myclubdetail'),
    path('myclubupdate/<int:pk>',views.MyClubUpDateView.as_view(),name='myclubupdate'),
    path('myclubdeletecheck/<int:pk>',views.MyClubDeleteCheckView.as_view(),name='myclubdeletecheck'),
    path('myclubdeletedone',views.MyClubDeleteDoneView.as_view(),name='myclubdeletedone'),
    #イベント機能
    path('eventpost',views.EventPostView.as_view(),name='eventpost'),
    path('eventpostdone',views.EventPostDoneView.as_view(),name='eventpostdone'),
    path('myeventlist',views.MyEventListView.as_view(),name='myeventlist'),
    path('myeventdetail/<int:pk>',views.MyEventDetailView.as_view(),name='myeventdetail'),
    path('myeventupdate/<int:pk>',views.MyEventUpDateView.as_view(),name='myeventupdate'),
    path('myeventdeletecheck/<int:pk>',views.MyEventDeleteCheckView.as_view(),name='myeventdeletecheck'),
    path('myeventdeletedone',views.MyEventDeleteDoneView.as_view(),name='myeventdeletedone'),
    #ブログ機能
    path('blogpost',views.BlogPostView.as_view(),name='blogpost'),
    path('blogpostcheck',views.BlogPostCheckView.as_view(),name='blogpostcheck'),
    path('mybloglist',views.MyBlogListView.as_view(),name='mybloglist'),
    path('myblogdetail/<int:pk>',views.MyBlogDetailView.as_view(),name='myblogdetail'),
    path('myblogupdate/<int:pk>',views.MyBlogUpDateView.as_view(),name='myblogupdate'),
    path('myblogdeletecheck/<int:pk>',views.MyBlogDeleteCheckView.as_view(),name='myblogdeletecheck'),
    path('myblogdeletedone',views.MyBlogDeleteDoneView.as_view(),name='myblogdeletedone'),
    #お問い合わせ機能
    path('contact',views.ContactView.as_view(),name='contact'),
    path('contactdone',views.ContactDoneView.as_view(),name='contactdone'),
    #フリースクールアカウント以外でアクセスしようとした時のエラーページ
    path('loginerror',views.LoginErrorView.as_view(),name='loginerror'),
]

freeschoolapp/views.py
from django.shortcuts import render,redirect
from django.views.generic.base import TemplateView
from django.views import View
from .models import CustomUser,FreeSchool,Club,Event,BlogPost
from .forms import ClubPostForm,EventPostForm,BlogPostForm,ContactForm,CustomUserForm,FreeSchoolForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView,ListView,DetailView,UpdateView,DeleteView,FormView
from django.urls import reverse_lazy
from studentapp.models import Student
from django.core.mail import EmailMessage
from django.contrib import messages

class TopView(TemplateView):
    #freeschool_top.htmlをレンダリング（描写）する
    template_name='freeschool_top.html'
    
    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)

#ユーザー検索画面
class UserSearchView(ListView):
    
    #freeschool_usersearch.htmlをレンダリング（描写）する
    template_name='freeschool_usersearch.html'
    
    #1ページに表示する件数
    paginate_by=10
    
    #モデルを指定する
    model=Student
    
    def get_queryset(self, **kwargs):
        queryset=super().get_queryset(**kwargs)
        query=self.request.GET.get('q','')

        if query!='':
            queryset=queryset.filter(nickname=query)

        return queryset.order_by('-id')

    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)

class UserDetailView(UpdateView):
    
    #freeschool_userdetail.htmlをレンダリング（描写）する
    template_name='freeschool_userdetail.html'

    #モデルを指定する
    model=Student
    
    #フィールドを指定する
    fields=('is_view',)
    
    def form_valid(self, form):
        messages.success(self.request, "閲覧権限を変更しました")
        return super().form_valid(form)
    
    success_url=reverse_lazy('freeschoolapp:usersearch')
    
    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)

class ClubPostView(CreateView):
    #サークル掲載情報登録画面を表示
    template_name='freeschool_clubpost.html'
    #フォームとモデルを指定する
    form_class=ClubPostForm
    form=ClubPostForm
    model=Club
    
    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        #投稿フォームをcontextに格納
        context['clubpost_form']=self.form
        return context
    
    def form_valid(self,form):
        #POSTされたデータを取得
        postdata=form.save(commit=False)
        #ユーザー情報を設定
        postdata.user=self.request.user
        #保存
        postdata.save()
        messages.success(self.request, "サークル情報を投稿しました")
        
        return super().form_valid(form)
    
    def get_success_url(self):
        #成功後の遷移先URL
        return reverse_lazy('freeschoolapp:clubpostdone')
    
    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)

class ClubPostDoneView(TemplateView):
    
    #freeschool_clubpostdone.htmlをレンダリングする（描写）する
    template_name='freeschool_clubpostdone.html'

    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)
   
class MyClubListView(ListView):
    
    #freeschool_myclublist.htmlをレンダリング（描写）する
    template_name='freeschool_myclublist.html'
    
    #投稿されたサークルを投稿日時の降順（新しい順）に並べ替える
    def get_queryset(self):
        # ユーザーの `uu_id` を使って、関連するサークルを取得
        return Club.objects.filter(user_id=self.request.user.uu_id).order_by('-created_at')

    #1ページに表示する件数
    paginate_by=10
    
    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)

class MyClubDetailView(DetailView):
    
    #freeschool_myclubdetail.htmlをレンダリング（描写）する
    template_name='freeschool_myclubdetail.html'
    
    #モデルを指定する
    model=Club
    
    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)
    
class MyClubUpDateView(UpdateView):
    
    #freeshool_myclubupdate.htmlをレンダリング（描写）する
    template_name='freeschool_myclubupdate.html'
    
    #フォームとモデルを指定する
    model=Club
    form_class=ClubPostForm
    
    def form_valid(self, form):
        messages.success(self.request, "サークル情報を更新しました")
        return super().form_valid(form)
    
    def get_success_url(self):
        #成功後の遷移先URL
        return reverse_lazy('freeschoolapp:myclubupdate', kwargs={'pk': self.object.pk})

    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)
    
class MyClubDeleteCheckView(DeleteView):
    
    #freeshool_myclubdeletecheck.htmlをレンダリング（描写）する
    template_name='freeschool_myclubdeletecheck.html'
    
    #モデルを指定する
    model=Club
    
    def form_valid(self, form):
        messages.success(self.request, "サークル情報を削除しました")
        return super().form_valid(form)
    
    def get_success_url(self):
        #成功後の遷移先URL
        return reverse_lazy('freeschoolapp:myclubdeletedone')
    
    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)

class MyClubDeleteDoneView(TemplateView):
    
    #freeshool_myclubderetedoneview.htmlをレンダリング（描写）する
    template_name='freeschool_myclubdeletedone.html'
    
    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)

class EventPostView(CreateView):

    #イベント掲載情報登録画面を表示
    template_name='freeschool_eventpost.html'
    #フォームとモデルを指定する
    form_class=EventPostForm
    form=EventPostForm
    model=Event
    
    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        #投稿フォームをcontextに格納
        context['eventpost_form']=self.form
        return context
    
    def form_valid(self,form):
        #POSTされたデータを取得
        postdata=form.save(commit=False)
        #ユーザー情報を設定
        postdata.user=self.request.user
        #保存
        postdata.save()
        messages.success(self.request, "イベント情報を投稿しました")
        
        return super().form_valid(form)
    
    def get_success_url(self):
        #成功後の遷移先URL
        return reverse_lazy('freeschoolapp:eventpostdone')

    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)

class EventPostDoneView(TemplateView):
    
    #freshool_eventpostdone.htmlをレンダリング（描写）する
    template_name='freeschool_eventpostdone.html'

    def dispatch(self, *args, **kwargs):
        # ログイン済みで user_type が 'freeschool' であるか確認
        if not(self.request.user.is_authenticated and self.request.user.user_type=='freeschool'):
            # 条件を満たさない場合はアクセス拒否または別ページへリダイレクト
            return redirect('freeschoolapp:loginerror')#ログインページにリダイレクト
        return super().dispatch(self.request,*args,**kwargs)

class MyEventListView(ListView):
    
    #freeschool_myeventlist.htmlをレンダリング（描写）する
    template_name='freeschool_myeventlist.html'
    
    #投稿されたイベントを投稿日時の降順（新しい順）に並べ替える
    def get_queryset(self):
        # ユーザーの `uu_id` を使って、関連するイベントを取得
        return Event.objects.filter(user_id=self.request.user.uu_id).order_by('-created_at')
    
    #1ページに表示する件数
    paginate_by=10

    def dispatch(self, *args, **kwargs):

freeschoolapp/templates/freeschool_accountupdate.html
{% extends 'freeschool_base.html' %}
{% block title %}freeschool accountupdate{% endblock %}
{% block contents %}
freeschool accountupdate
<a href="{% url 'freeschoolapp:mypage' %}"><button>変更する</button></a>
{% endblock %}

freeschoolapp/templates/freeschool_base.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script> -->
    <link href="{% static 'css/freeschool.css' %}"  rel="stylesheet" />
</head>
<body>
    <div class="container" style="display: flex;"> 
        <!--ログインされている場合-->
        {% if user.is_authenticated %}
            <div id="menu">
                <a href="{% url 'freeschoolapp:top' %}">メインメニュー</a>
                <!--サークルタブ-->
                <div onclick="obj=document.getElementById('openclub').style; obj.display=(obj.display=='none')?'block':'none';">
                    <a class="menu_item" style="cursor:pointer;">サークル▼</a>
                </div>
                <div id="openclub" style="display:none;clear:both;">
                    <a class="menu_item" href="{% url 'freeschoolapp:clubpost' %}">・サークル掲載</a>
                    <br>
                    <a class="menu_item" href="{% url 'freeschoolapp:myclublist' %}">・管理サークル一覧</a>
                </div>
                <!--イベントタブ-->
                <div onclick="obj=document.getElementById('openevent').style; obj.display=(obj.display=='none')?'block':'none';">
                    <a class="menu_item" style="cursor:pointer;">イベント▼</a>
                </div>
                <div id="openevent" style="display:none;clear:both;">
                    <a class="menu_item" href="{% url 'freeschoolapp:eventpost' %}">・イベント掲載</a>
                    <br>
                    <a class="menu_item" href="{% url 'freeschoolapp:myeventlist' %}">・掲載イベント一覧</a>
                </div>
                <!--ブログタブ-->
                <div onclick="obj=document.getElementById('openblog').style; obj.display=(obj.display=='none')?'block':'none';">
                    <a class="menu_item" style="cursor:pointer;">ブログ▼</a>
                </div>
                <div id="openblog" style="display:none;clear:both;">
                    <a class="menu_item" href="{% url 'freeschoolapp:blogpost' %}">・ブログ記事投稿</a>
                    <br>
                    <a class="menu_item" href="{% url 'freeschoolapp:mybloglist' %}">・投稿ブログ記事一覧</a>
                </div>
                <!--ユーザー管理タブ-->
                <div onclick="obj=document.getElementById('openusermanage').style; obj.display=(obj.display=='none')?'block':'none';">
                    <a class="menu_item" style="cursor:pointer;">ユーザー管理▼</a>
                </div>
                <div id="openusermanage" style="display:none;clear:both;">
                    <a class="menu_item" href="{% url 'freeschoolapp:usersearch' %}">・ユーザー検索</a>
                </div>
                <!--アカウントタブ-->
                <div onclick="obj=document.getElementById('openaccount').style; obj.display=(obj.display=='none')?'block':'none';">
                    <a class="menu_item" style="cursor:pointer;">アカウント▼</a>
                </div>
                <div id="openaccount" style="display:none;clear:both;">
                    <a class="menu_item" href="{% url 'freeschoolapp:mypage' %}">・アカウント情報</a>
                    <br>
                    <a class="menu_item" href="{% url 'accounts:logout' %}">・ログアウト</a>
                </div>
                <a class="menu_item" href="{% url 'freeschoolapp:contact' %}">お問い合わせ</a>
            </div>
                <div id="contents"> 
                
                {% for message in messages %}
                <div {% if message.tags %}class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </div>
                {% endfor %} 
                <div class="content-inner">
        
                {% block contents %}
                    <!-- ここにコンテンツが挿入されます -->
                {% endblock %}
                </div>
        {% endif %}
    </div>
</body>
</html>

freeschoolapp/templates/freeschool_contactdone.html
{% extends 'freeschool_base.html' %}
{% block title %}フリースクール関係者お問い合わせ完了画面{% endblock %}
{% block contents %}
フリースクール関係者お問い合わせ完了画面
<a href="{% url 'freeschoolapp:top' %}"><button>メインメニューに戻る</button></a>
{% endblock %}

freeschoolapp/templates/freeschool_eventpostdone.html
{% extends 'freeschool_base.html' %}
{% block title %}イベント掲載完了画面{% endblock %}
{% block contents %}
イベント掲載完了画面
<a href="{% url 'freeschoolapp:myeventlist' %}"><button>掲載イベント一覧に戻る</button></a>
{% endblock %}

freeschoolapp/templates/freeschool_loginerror.html
フリースクールアカウントでログインしてください<br>
<a href="{% url 'accounts:login' %}"><button>ログイン</button></a>

freeschoolapp/templates/freeschool_myblogdeletecheck.html
{% extends 'freeschool_base.html' %}
{% block title %}投稿ブログ記事削除確認画面{% endblock %}
{% block contents %}
投稿ブログ記事削除確認画面
<br>
ブログ記事タイトル:{{ object.title }}
<br>
このブログ記事を削除しますか?

<form method="post" id="requestForm">
    {% csrf_token %}
    <button type="submit" id="submitButton">はい</button>
    <a href="{% url 'freeschoolapp:myblogdetail' object.pk %}" class="cssbutton">いいえ</a>
</form>

<!--2重submitを防止する処理-->
<script>
    const form = document.getElementById("requestForm");
    const submitButton = document.getElementById("submitButton");

    form.addEventListener("submit", function(event){
        submitButton.disabled = true;//ボタンを無効化
    });
</script>


{% endblock %}

freeschoolapp/templates/freeschool_mybloglist.html
{% extends 'freeschool_base.html' %}
{% block title %}投稿ブログ記事一覧画面{% endblock %}
{% block contents %}
投稿ブログ記事一覧画面
<a href="{% url 'freeschoolapp:top' %}"><button>メインメニューに戻る</button></a>
<br>
{% if object_list %}
    {% for record in object_list %}
        {% if user.uu_id == record.user_id %}
            {{ record.id }}
            {{ record.title }}
            <a href="{% url 'freeschoolapp:myblogdetail' record.pk %}">詳細</a>
            <br>
        {% endif %}
    {% endfor %}

    {% include 'pagination.html' %}
{% else %}
<br>
投稿されているブログ記事はありません
{% endif %}

{% endblock %}

freeschoolapp/templates/freeschool_myclubdeletecheck.html
{% extends 'freeschool_base.html' %}
{% block title %}管理サークル削除確認画面{% endblock %}
{% block contents %}
管理サークル削除確認画面
<br>
サークル名:{{ object.club_name }}
<br>
このサークルを削除しますか?
<form method="post" id="requestForm">
    {% csrf_token %}
    <button type="submit" id="submitButton">はい</button>
    <a href="{% url 'freeschoolapp:myclubdetail' object.pk %}" class="cssbutton">いいえ</a>
</form>

<!--2重submitを防止する処理-->
<script>
    const form = document.getElementById("requestForm");
    const submitButton = document.getElementById("submitButton");

    form.addEventListener("submit", function(event){
        submitButton.disabled = true;//ボタンを無効化
    });
</script>


{% endblock %}

freeschoolapp/templates/freeschool_myclubdetail.html
{% extends 'freeschool_base.html' %}
{% block title %}管理サークル詳細画面{% endblock %}
{% block contents %}
管理サークル詳細画面
<a href="{% url 'freeschoolapp:myclublist' %}"><button>管理サークル一覧へ戻る</button></a>
<a href="{% url 'freeschoolapp:myclubupdate' object.id %}"><button>変更</button></a>
<a href="{% url 'freeschoolapp:myclubdeletecheck' object.id %}"><button>削除</button></a>
<br><br>
<div class="detail">
    <table>
        <tbody>
            <tr>
                <th>サークルID</th>
                <td>{{ object.id }}</td>
            </tr>
            <tr>
                <th>サークル名</th>
                <td>{{ object.club_name }}</td>
            </tr>
            <tr>
                <th>掲載日時</th>
                <td>{{ object.created_at }}</td>
            </tr>
            <tr>
                <th>ジャンル</th>
                <td>
                    {% if object.category == 'culture' %}
                        文化
                    {% elif object.category == 'sports' %}
                        運動
                    {% elif object.category == 'study' %}
                        勉強
                    {% else %}
                        その他
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>代表者名</th>
                <td>{{ object.REP }}</td>
            </tr>
            <tr>
                <th>メールアドレス</th>
                <td>{{ object.email }}</td>
            </tr>
            <tr>
                <th>電話番号</th>
                <td>{{ object.phone_number }}</td>
            </tr>
            <tr>
                <th>日時</th>
                <td>{{ object.date }}</td>
            </tr>
            <tr>
                <th>参加費</th>
                <td>{{ object.fee }}</td>
            </tr>
            <tr>
                <th>活動場所</th>
                <td>{{ object.place }}</td>
            </tr>
            <tr>
                <th>SNSリンク</th>
                <td>{{ object.sns_link }}</td>
            </tr>
            <tr>
                <th>サークルの紹介画像①</th>
                <td><img src="{{ object.image1.url }}" width="100%" height="100%"></td>
            </tr>
            <tr>
                <th>サークルの紹介画像②</th>
                <td>
                    {% if object.image2 %}
                        <img src="{{ object.image2.url }}" width="100%" height="100%">
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>サークルの紹介画像③</th>
                <td>
                    {% if object.image3 %}
                        <img src="{{ object.image3.url }}" width="100%" height="100%">
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>サークルの紹介画像④</th>
                <td>
                    {% if object.image4 %}
                        <img src="{{ object.image4.url }}" width="100%" height="100%">
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>サークルの紹介画像⑤</th>
                <td>
                    {% if object.image5 %}
                        <img src="{{ object.image5.url }}" width="100%" height="100%">
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>サークルの紹介文</th>
                <td>{{ object.detail_text }}</td>
            </tr>
            <tr>
                <th>公開状況</th>
                <td>
                    {% if object.public_flag %}
                        全てのユーザーに公開中
                    {% else %}
                        限定公開
                    {% endif %}
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}